-- Tablas principales
CREATE TABLE perfiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  nombre TEXT NOT NULL,
  puntos_totales INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE partidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local TEXT NOT NULL,
  visitante TEXT NOT NULL,
  fecha TIMESTAMP WITH TIME ZONE NOT NULL,
  goles_local INTEGER,
  goles_visitante INTEGER,
  estado TEXT DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'jugado')),
  grupo TEXT
);

CREATE TABLE predicciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  partido_id BIGINT REFERENCES partidos ON DELETE CASCADE NOT NULL,
  goles_local INTEGER NOT NULL,
  goles_visitante INTEGER NOT NULL,
  puntos INTEGER DEFAULT 0,
  UNIQUE(user_id, partido_id)
);

-- Lógica de Puntos (Función y Trigger)
CREATE OR REPLACE FUNCTION calcular_puntos_prediccion()
RETURNS TRIGGER AS $$
DECLARE
  v_goles_local_real INTEGER;
  v_goles_visitante_real INTEGER;
  v_puntos INTEGER := 0;
BEGIN
  -- Obtener resultado real del partido
  SELECT goles_local, goles_visitante INTO v_goles_local_real, v_goles_visitante_real
  FROM partidos WHERE id = NEW.partido_id AND estado = 'jugado';

  IF FOUND THEN
    -- 3 puntos por resultado exacto
    IF NEW.goles_local = v_goles_local_real AND NEW.goles_visitante = v_goles_visitante_real THEN
      v_puntos := 3;
    -- 1 punto por ganador/empate (pero no exacto)
    ELSIF (NEW.goles_local > NEW.goles_visitante AND v_goles_local_real > v_goles_visitante_real) OR
          (NEW.goles_local < NEW.goles_visitante AND v_goles_local_real < v_goles_visitante_real) OR
          (NEW.goles_local = NEW.goles_visitante AND v_goles_local_real = v_goles_visitante_real) THEN
      v_puntos := 1;
    END IF;

    UPDATE predicciones SET puntos = v_puntos WHERE id = NEW.id;
    
    -- Actualizar puntos totales del perfil
    UPDATE perfiles SET puntos_totales = (
      SELECT SUM(puntos) FROM predicciones WHERE user_id = NEW.user_id
    ) WHERE id = NEW.user_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger para actualizar puntos cuando se inserta/actualiza una predicción
-- y cuando el partido cambia a 'jugado' (esto último requeriría otro trigger o lógica en app)

-- Función para actualizar puntos de todas las predicciones de un partido
CREATE OR REPLACE FUNCTION actualizar_puntos_partido()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.estado = 'jugado' AND (OLD.estado = 'pendiente' OR OLD.goles_local IS DISTINCT FROM NEW.goles_local OR OLD.goles_visitante IS DISTINCT FROM NEW.goles_visitante) THEN
    -- Actualizar puntos de cada predicción
    UPDATE predicciones
    SET puntos = CASE
      WHEN predicciones.goles_local = NEW.goles_local AND predicciones.goles_visitante = NEW.goles_visitante THEN 3
      WHEN (predicciones.goles_local > predicciones.goles_local AND NEW.goles_local > NEW.goles_visitante) OR
           (predicciones.goles_local < predicciones.goles_visitante AND NEW.goles_local < NEW.goles_visitante) OR
           (predicciones.goles_local = predicciones.goles_visitante AND NEW.goles_local = NEW.goles_visitante) THEN 1
      ELSE 0
    END
    WHERE partido_id = NEW.id;

    -- Actualizar perfiles
    UPDATE perfiles p
    SET puntos_totales = (
      SELECT COALESCE(SUM(puntos), 0)
      FROM predicciones
      WHERE user_id = p.id
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_actualizar_puntos_partido
AFTER UPDATE ON partidos
FOR EACH ROW EXECUTE FUNCTION actualizar_puntos_partido();

-- RLS (Row Level Security)
ALTER TABLE perfiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE partidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE predicciones ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Perfiles visibles para todos" ON perfiles FOR SELECT USING (true);
CREATE POLICY "Partidos visibles para todos" ON partidos FOR SELECT USING (true);
CREATE POLICY "Predicciones propias visibles para el usuario" ON predicciones FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Usuarios pueden insertar sus propias predicciones" ON predicciones FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Usuarios pueden actualizar sus propias predicciones" ON predicciones FOR UPDATE USING (auth.uid() = user_id);

